name: KristaDalton
favicon: null
layout_spectrum: 0.35256
typography_spectrum: 0.7083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5625
  lightness: 0.8018538500182331
  saturation: 0.45993257546797395
  rhythmicContrast: 0.532144526951015
purpose: []
